---
version: '2'
services:

  ## Config Servers
  config01:
    image: mongo
    command: mongod --port 27017 --configsvr --replSet configserver --noprealloc
      --smallfiles --oplogSize 16
    volumes:
    - ./scripts:/scripts
  config02:
    image: mongo
    command: mongod --port 27017 --configsvr --replSet configserver --noprealloc
      --smallfiles --oplogSize 16
    volumes:
    - ./scripts:/scripts
  config03:
    image: mongo
    command: mongod --port 27017 --configsvr --replSet configserver --noprealloc
      --smallfiles --oplogSize 16
    volumes:
    - ./scripts:/scripts

  ## Shards
  shard1-rs-a:
    image: mongo
    command: mongod --port 27018 --shardsvr --replSet shard1-rs --noprealloc --smallfiles
      --oplogSize 16
    volumes:
    - ./scripts:/scripts
  shard1-rs-b:
    image: mongo
    command: mongod --port 27018 --shardsvr --replSet shard1-rs --noprealloc --smallfiles
      --oplogSize 16
    volumes:
    - ./scripts:/scripts
  shard1-rs-c:
    image: mongo
    command: mongod --port 27018 --shardsvr --replSet shard1-rs --noprealloc --smallfiles
      --oplogSize 16
    volumes:
    - ./scripts:/scripts

  ## Router
  router:
    image: mongo
    command: mongos --port 27017 --configdb configserver/config01:27017,config02:27017,config03:27017
      --bind_ip_all
    ports:
    - 27017:27017
    volumes:
    - ./scripts:/scripts
    depends_on:
    - config01
    - config02
    - config03
    - shard1-rs-a
    - shard1-rs-b
    - shard1-rs-c
